[colors.primary]
background = "#24292e"
foreground = "#f6f8fa"

[colors.cursor]
cursor = "#85e89d"
text = "#24292e"

[colors.selection]
background = "#c8c8fa"
text = "#24292e"

[colors.normal]
black = "#24292e"
red = "#f97583"
green = "#85e89d"
yellow = "#ffea7f"
blue = "#79b8ff"
magenta = "#b392f0"
cyan = "#73e3ff"
white = "#f6f8fa"

[colors.bright]
black = "#959da5"
red = "#f97583"
green = "#85e89d"
yellow = "#ffea7f"
blue = "#79b8ff"
magenta = "#b392f0"
cyan = "#73e3ff"
white = "#f6f8fa"
