-- Auto-generated from palette.json — do not edit manually
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.g.colors_name = "colors"

local hl = vim.api.nvim_set_hl
local function link(from, to) hl(0, from, { link = to }) end

-- Terminal palette
vim.g.terminal_color_0 = "#24292e"
vim.g.terminal_color_1 = "#f97583"
vim.g.terminal_color_2 = "#85e89d"
vim.g.terminal_color_3 = "#ffea7f"
vim.g.terminal_color_4 = "#79b8ff"
vim.g.terminal_color_5 = "#b392f0"
vim.g.terminal_color_6 = "#73e3ff"
vim.g.terminal_color_7 = "#f6f8fa"
vim.g.terminal_color_8 = "#959da5"
vim.g.terminal_color_9 = "#f97583"
vim.g.terminal_color_10 = "#85e89d"
vim.g.terminal_color_11 = "#ffea7f"
vim.g.terminal_color_12 = "#79b8ff"
vim.g.terminal_color_13 = "#b392f0"
vim.g.terminal_color_14 = "#73e3ff"
vim.g.terminal_color_15 = "#f6f8fa"

-- Editor UI
hl(0, "Normal",       { fg = "#f6f8fa", bg = "#24292e" })
hl(0, "NormalFloat",  { fg = "#f6f8fa", bg = "#2f363d" })
hl(0, "FloatBorder",  { fg = "#959da5", bg = "#2f363d" })
hl(0, "FloatTitle",   { fg = "#79b8ff", bg = "#2f363d", bold = true })
hl(0, "Cursor",       { fg = "#24292e", bg = "#85e89d" })
hl(0, "CursorLine",   { bg = "#2f363d" })
hl(0, "CursorColumn", { bg = "#2f363d" })
hl(0, "ColorColumn",  { bg = "#2f363d" })
hl(0, "LineNr",       { fg = "#959da5" })
hl(0, "CursorLineNr", { fg = "#f6f8fa", bold = true })
hl(0, "SignColumn",   { bg = "NONE" })
hl(0, "Visual",       { fg = "#24292e", bg = "#c8c8fa" })
hl(0, "VisualNOS",    { bg = "#c8c8fa" })
hl(0, "Search",       { fg = "#24292e", bg = "#fefb52" })
hl(0, "IncSearch",    { fg = "#24292e", bg = "#fefb52" })
hl(0, "CurSearch",    { fg = "#24292e", bg = "#fefb52" })
hl(0, "MatchParen",   { fg = "#ffea7f", bold = true, underline = true })
hl(0, "NonText",      { fg = "#959da5" })
hl(0, "Whitespace",   { fg = "#2f363d" })
hl(0, "EndOfBuffer",  { fg = "#24292e" })
hl(0, "Directory",    { fg = "#79b8ff" })
hl(0, "Title",        { fg = "#79b8ff", bold = true })
hl(0, "WinSeparator", { fg = "#2f363d" })
hl(0, "VertSplit",    { fg = "#2f363d" })
hl(0, "StatusLine",   { fg = "#f6f8fa", bg = "#2f363d" })
hl(0, "StatusLineNC", { fg = "#959da5", bg = "#2f363d" })
hl(0, "TabLine",      { fg = "#959da5", bg = "#2f363d" })
hl(0, "TabLineSel",   { fg = "#f6f8fa", bg = "#24292e", bold = true })
hl(0, "TabLineFill",  { bg = "#2f363d" })
hl(0, "WinBar",       { fg = "#f6f8fa", bg = "#24292e" })
hl(0, "WinBarNC",     { fg = "#959da5", bg = "#24292e" })
hl(0, "Folded",       { fg = "#959da5", bg = "#2f363d" })
hl(0, "FoldColumn",   { fg = "#959da5" })
hl(0, "Pmenu",        { fg = "#f6f8fa", bg = "#2f363d" })
hl(0, "PmenuSel",     { fg = "#24292e", bg = "#79b8ff", bold = true })
hl(0, "PmenuSbar",    { bg = "#2f363d" })
hl(0, "PmenuThumb",   { bg = "#959da5" })
hl(0, "WildMenu",     { fg = "#24292e", bg = "#79b8ff" })
hl(0, "ModeMsg",      { fg = "#f6f8fa", bold = true })
hl(0, "MoreMsg",      { fg = "#79b8ff" })
hl(0, "Question",     { fg = "#79b8ff" })
hl(0, "ErrorMsg",     { fg = "#f97583", bold = true })
hl(0, "WarningMsg",   { fg = "#ffea7f" })
hl(0, "SpecialKey",   { fg = "#959da5" })
hl(0, "Conceal",      { fg = "#959da5" })

-- Classic syntax
hl(0, "Comment",         { fg = "#959da5", italic = true })
hl(0, "Constant",        { fg = "#73e3ff" })
hl(0, "String",          { fg = "#85e89d" })
hl(0, "Character",       { fg = "#85e89d" })
hl(0, "Number",          { fg = "#b392f0" })
hl(0, "Boolean",         { fg = "#b392f0" })
hl(0, "Float",           { fg = "#b392f0" })
hl(0, "Identifier",      { fg = "#f6f8fa" })
hl(0, "Function",        { fg = "#79b8ff" })
hl(0, "Statement",       { fg = "#f97583" })
hl(0, "Conditional",     { fg = "#f97583" })
hl(0, "Repeat",          { fg = "#f97583" })
hl(0, "Label",           { fg = "#f97583" })
hl(0, "Operator",        { fg = "#f6f8fa" })
hl(0, "Keyword",         { fg = "#f97583" })
hl(0, "Exception",       { fg = "#f97583" })
hl(0, "PreProc",         { fg = "#b392f0" })
hl(0, "Include",         { fg = "#b392f0" })
hl(0, "Define",          { fg = "#b392f0" })
hl(0, "Macro",           { fg = "#b392f0" })
hl(0, "PreCondit",       { fg = "#b392f0" })
hl(0, "Type",            { fg = "#ffea7f" })
hl(0, "StorageClass",    { fg = "#ffea7f" })
hl(0, "Structure",       { fg = "#ffea7f" })
hl(0, "Typedef",         { fg = "#ffea7f" })
hl(0, "Special",         { fg = "#73e3ff" })
hl(0, "SpecialChar",     { fg = "#73e3ff" })
hl(0, "Tag",             { fg = "#f97583" })
hl(0, "Delimiter",       { fg = "#f6f8fa" })
hl(0, "SpecialComment",  { fg = "#73e3ff", italic = true })
hl(0, "Debug",           { fg = "#f97583" })
hl(0, "Underlined",      { fg = "#79b8ff", underline = true })
hl(0, "Todo",            { fg = "#ffea7f", bold = true })
hl(0, "Error",           { fg = "#f97583", bold = true })

-- Treesitter (@-captures)
link("@comment",              "Comment")
link("@string",               "String")
link("@string.escape",        "Special")
link("@character",            "Character")
link("@number",               "Number")
link("@boolean",              "Boolean")
link("@float",                "Float")
link("@function",             "Function")
link("@function.call",        "Function")
hl(0, "@function.builtin",   { fg = "#73e3ff" })
link("@function.macro",       "Macro")
link("@method",               "Function")
link("@method.call",          "Function")
link("@constructor",          "Type")
hl(0, "@parameter",          { fg = "#f6f8fa" })
link("@keyword",              "Keyword")
link("@keyword.function",     "Keyword")
link("@keyword.operator",     "Keyword")
link("@keyword.return",       "Keyword")
link("@conditional",          "Conditional")
link("@repeat",               "Repeat")
link("@label",                "Label")
link("@operator",             "Operator")
link("@exception",            "Exception")
link("@variable",             "Identifier")
hl(0, "@variable.builtin",   { fg = "#73e3ff" })
hl(0, "@variable.member",    { fg = "#73e3ff" })
hl(0, "@field",              { fg = "#73e3ff" })
hl(0, "@property",           { fg = "#73e3ff" })
link("@constant",             "Constant")
hl(0, "@constant.builtin",   { fg = "#73e3ff" })
link("@constant.macro",       "Macro")
link("@type",                 "Type")
hl(0, "@type.builtin",       { fg = "#ffea7f" })
link("@type.definition",      "Typedef")
hl(0, "@namespace",          { fg = "#ffea7f" })
hl(0, "@module",             { fg = "#ffea7f" })
link("@include",              "Include")
link("@punctuation",          "Delimiter")
link("@punctuation.bracket",  "Delimiter")
link("@punctuation.delimiter","Delimiter")
link("@punctuation.special",  "Special")
hl(0, "@tag",                { fg = "#f97583" })
hl(0, "@tag.attribute",      { fg = "#ffea7f" })
hl(0, "@tag.delimiter",      { fg = "#f6f8fa" })
hl(0, "@text",               { fg = "#f6f8fa" })
hl(0, "@text.strong",         { bold = true })
hl(0, "@text.emphasis",       { italic = true })
hl(0, "@text.underline",      { underline = true })
hl(0, "@text.title",         { fg = "#79b8ff", bold = true })
hl(0, "@text.literal",       { fg = "#85e89d" })
hl(0, "@text.uri",           { fg = "#79b8ff", underline = true })
hl(0, "@text.todo",          { fg = "#ffea7f", bold = true })
hl(0, "@text.note",          { fg = "#79b8ff", bold = true })
hl(0, "@text.warning",       { fg = "#ffea7f", bold = true })
hl(0, "@text.danger",        { fg = "#f97583", bold = true })
hl(0, "@text.diff.add",      { fg = "#85e89d" })
hl(0, "@text.diff.delete",   { fg = "#f97583" })

-- LSP semantic tokens
link("@lsp.type.function",   "Function")
link("@lsp.type.method",     "Function")
link("@lsp.type.variable",   "Identifier")
link("@lsp.type.parameter",  "@parameter")
link("@lsp.type.property",   "@property")
link("@lsp.type.type",       "Type")
link("@lsp.type.struct",     "Structure")
link("@lsp.type.enum",       "Type")
link("@lsp.type.enumMember", "Constant")
link("@lsp.type.interface",  "Type")
link("@lsp.type.class",      "Type")
link("@lsp.type.namespace",  "@namespace")
link("@lsp.type.macro",      "Macro")
link("@lsp.type.keyword",    "Keyword")
link("@lsp.type.string",     "String")
link("@lsp.type.comment",    "Comment")

-- Diagnostics
hl(0, "DiagnosticError", { fg = "#f97583" })
hl(0, "DiagnosticWarn",  { fg = "#ffea7f" })
hl(0, "DiagnosticInfo",  { fg = "#79b8ff" })
hl(0, "DiagnosticHint",  { fg = "#73e3ff" })
hl(0, "DiagnosticOk",    { fg = "#85e89d" })
hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#f97583" })
hl(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#ffea7f" })
hl(0, "DiagnosticUnderlineInfo",  { undercurl = true, sp = "#79b8ff" })
hl(0, "DiagnosticUnderlineHint",  { undercurl = true, sp = "#73e3ff" })
link("DiagnosticVirtualTextError", "DiagnosticError")
link("DiagnosticVirtualTextWarn",  "DiagnosticWarn")
link("DiagnosticVirtualTextInfo",  "DiagnosticInfo")
link("DiagnosticVirtualTextHint",  "DiagnosticHint")

-- Diff
hl(0, "DiffAdd",    { fg = "#85e89d",  bg = "#2f363d" })
hl(0, "DiffChange", { fg = "#79b8ff",   bg = "#2f363d" })
hl(0, "DiffDelete", { fg = "#f97583",    bg = "#2f363d" })
hl(0, "DiffText",   { fg = "#ffea7f", bg = "#2f363d", bold = true })

-- Gitsigns
hl(0, "GitSignsAdd",    { fg = "#85e89d" })
hl(0, "GitSignsChange", { fg = "#79b8ff" })
hl(0, "GitSignsDelete", { fg = "#f97583" })

-- Telescope
link("TelescopeBorder",        "FloatBorder")
link("TelescopePromptBorder",  "FloatBorder")
link("TelescopeResultsBorder", "FloatBorder")
link("TelescopePreviewBorder", "FloatBorder")
hl(0, "TelescopeSelection",   { bg = "#2f363d", bold = true })
hl(0, "TelescopeMatching",    { fg = "#fefb52", bold = true })
hl(0, "TelescopePromptPrefix",{ fg = "#79b8ff" })

-- nvim-cmp
link("CmpItemAbbr",            "Pmenu")
hl(0, "CmpItemAbbrMatch",     { fg = "#fefb52", bold = true })
hl(0, "CmpItemAbbrMatchFuzzy",{ fg = "#fefb52", bold = true })
hl(0, "CmpItemAbbrDeprecated",{ fg = "#959da5", strikethrough = true })
hl(0, "CmpItemKindFunction",  { fg = "#79b8ff" })
hl(0, "CmpItemKindMethod",    { fg = "#79b8ff" })
hl(0, "CmpItemKindVariable",  { fg = "#f6f8fa" })
hl(0, "CmpItemKindKeyword",   { fg = "#f97583" })
hl(0, "CmpItemKindClass",     { fg = "#ffea7f" })
hl(0, "CmpItemKindInterface", { fg = "#ffea7f" })
hl(0, "CmpItemKindModule",    { fg = "#ffea7f" })
hl(0, "CmpItemKindSnippet",   { fg = "#b392f0" })
hl(0, "CmpItemKindText",      { fg = "#f6f8fa" })
hl(0, "CmpItemMenu",          { fg = "#959da5" })

-- Trouble
link("TroubleNormal",       "NormalFloat")
hl(0, "TroubleText",       { fg = "#f6f8fa" })
hl(0, "TroubleCount",      { fg = "#b392f0" })
link("TroubleFile",         "Directory")
link("TroubleSource",       "Comment")

-- Indent-blankline (v3)
hl(0, "IblIndent",         { fg = "#2f363d" })
hl(0, "IblScope",          { fg = "#959da5" })

-- Misc references kept for downstream use
-- link=#79b8ff badge=#b392f0
